cloud:
  aws:
    credentials:
      access-key: AKIASIDRKPRRAEUR3ZPL
      secret-key: 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
    region:
      static: us-west-1
    stack:
      auto: false

application:
  bucket:
    name: groupten


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090